name: Deploy to GKE

on:
  push:
    branches:
      - main # Adjust this as necessary for your workflow

jobs:
  setup-build-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |-
          gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |-
          PROJECT_VERSION=$(cat ./package.json | grep '"version":' | sed 's/[^0-9.]//g')
          IMAGE_URI="gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-esg-app:$PROJECT_VERSION"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  deploy:
    name: Deploy to GKE
    needs: setup-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure kubectl
        run: |-
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy to GKE
        run: |-
          PROJECT_VERSION=$(cat ./package.json | grep '"version":' | sed 's/[^0-9.]//g')
          IMAGE_URI="gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-esg-app:$PROJECT_VERSION"
          kubectl set image deployment/iot-esg-app-deployment iot-esg-container=$IMAGE_URI
